### ISSUE TITLE
Route [admin] not defined. 

### ISSUE THREAD

**Issue by JavierOrellanaR** [Cloud5Ideas/appkit#2]
i've got this message after a laravel fresh install (i've followed all the steps to install and configure it with appkit)

ErrorException in UrlGenerator.php line 273:
Route [admin] not defined. (View: /var/www/html/.../resources/views/welcome.blade.php)

after this i tried to check if the routes were OK, so i did an "artisan route:list" on the console, and all i get is the "/" route.... is that normal?

**Comment by JavierOrellanaR** [comment]
ehmm... i've found the solution.... i just forgot to use caps on the module path on the config file >_<

'modules_path' => app_path('Modules'),

sorry for the mistake....

**Comment by Cloud5Ideas** [comment]
Not a problem at all. Happy coding... :)
